# Generated by Django 4.2.8 on 2023-12-13 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0002_member_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='image',
            field=models.ImageField(null=True, upload_to='media', verbose_name='Фото участника'),
        ),
    ]
